#!/usr/bin/env python3
"""Check, index and archive Toucan docs by their YAML status header.

  docs_status.py check                      exit 1 if a doc lacks a valid header or sits in the wrong place
  docs_status.py index                      rewrite docs/INDEX.md from the headers
  docs_status.py list [--status S]          print path, status, progress, summary
  docs_status.py archive PATH... --reason R move done/deprecated docs to docs/archive/ (specs to docs/specs/); deprecated names get -deprecated

No third-party packages. Run from anywhere inside the repo.
"""
import argparse, datetime, os, re, subprocess, sys
from pathlib import Path

ROOT = Path(subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True,
                           cwd=Path(__file__).resolve().parent).stdout.strip() or ".")
STATUSES = {"active", "in-progress", "planned", "reference", "done", "deprecated"}
ARCHIVED = {"done", "deprecated"}
SCOPE = ["docs", "Toucan.Core/ARCHITECTURE.md", "packaging/README.md"]
SKIP = {"docs/INDEX.md"}
OPEN_ONLY = ("docs/todos/", "docs/known-bugs.md")  # trackers: no ticked items
SHIPPED_ONLY = ("docs/completed-features.md",)  # no unchecked items
ARCHIVE_DIR = "docs/archive"
SPECS_DIR = "docs/specs"
FM = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def today():
    return datetime.date.today().isoformat()


def docs():
    for entry in SCOPE:
        p = ROOT / entry
        files = [p] if p.is_file() else sorted(p.rglob("*.md")) if p.exists() else []
        for f in files:
            rel = f.relative_to(ROOT).as_posix()
            if rel not in SKIP:
                yield f, rel


def parse(text):
    m = FM.match(text)
    if not m:
        return None
    meta = {}
    for line in m.group(1).splitlines():
        k, sep, v = line.partition(":")
        if sep and not line.startswith((" ", "#")):
            meta[k.strip()] = v.strip().strip("\"'")
    return meta


def check():
    bad = []
    for f, rel in docs():
        meta = parse(f.read_text(encoding="utf-8"))
        if meta is None:
            bad.append(f"{rel}: no YAML header"); continue
        for key in ("title", "status", "updated", "summary"):
            if not meta.get(key):
                bad.append(f"{rel}: missing '{key}'")
        st = meta.get("status")
        if st and st not in STATUSES:
            bad.append(f"{rel}: status '{st}' not one of {sorted(STATUSES)}")
        if meta.get("updated") and not re.fullmatch(r"\d{4}-\d\d-\d\d", meta["updated"]):
            bad.append(f"{rel}: 'updated' must be YYYY-MM-DD")
        body = f.read_text(encoding="utf-8")
        if rel.startswith(OPEN_ONLY) and re.search(r"^\s*- \[[xX]\]", body, re.M):
            bad.append(f"{rel}: tracker lists open work only; delete ticked '- [x]' items (changelog and completed-features keep them)")
        if rel in SHIPPED_ONLY and re.search(r"^\s*- \[ \]", body, re.M):
            bad.append(f"{rel}: lists shipped features only; move unchecked '- [ ]' items to the roadmap")
        in_archive = rel.startswith(ARCHIVE_DIR + "/")
        in_specs = rel.startswith(SPECS_DIR + "/")
        if st in ARCHIVED and not (in_archive or in_specs):
            bad.append(f"{rel}: status '{st}' belongs in {ARCHIVE_DIR}/ or {SPECS_DIR}/ (run: archive)")
        if st in STATUSES - ARCHIVED and in_archive:
            bad.append(f"{rel}: in {ARCHIVE_DIR}/ but status is '{st}'")
        if st in ARCHIVED and not (meta.get("archived") and meta.get("reason")):
            bad.append(f"{rel}: archived docs need 'archived' and 'reason'")
        if st == "deprecated" and not f.stem.endswith("-deprecated"):
            bad.append(f"{rel}: deprecated docs end in '-deprecated.md'")
        if st != "deprecated" and f.stem.endswith("-deprecated"):
            bad.append(f"{rel}: '-deprecated' in the name but status is '{st}'")
    print("\n".join(bad) if bad else "docs ok")
    return 1 if bad else 0


def rows():
    out = []
    for f, rel in docs():
        meta = parse(f.read_text(encoding="utf-8")) or {}
        out.append((rel, meta))
    return out


def index():
    groups = {"Current": [], "Archive": []}
    for rel, m in rows():
        groups["Archive" if m.get("status") in ARCHIVED else "Current"].append((rel, m))
    lines = ["---", "title: Docs index", "status: active", f"updated: {today()}",
             "summary: Generated table of every doc with its status, progress and summary; do not edit by hand.",
             "---", "", "# Docs index", "",
             "Generated by `.agents/skills/doc-status/scripts/docs_status.py index`. Edit the header in each doc, not this file.", ""]
    for name, items in groups.items():
        lines += [f"## {name}", "", "| Doc | Status | Progress | Updated | Summary |", "|---|---|---|---|---|"]
        order = {s: i for i, s in enumerate(["in-progress", "active", "planned", "reference", "done", "deprecated"])}
        for rel, m in sorted(items, key=lambda x: (order.get(x[1].get("status"), 9), x[0])):
            link = os.path.relpath(ROOT / rel, ROOT / "docs").replace(os.sep, "/")
            cell = lambda k: (m.get(k) or "").replace("|", "\\|")
            lines.append(f"| [{rel}]({link}) | {cell('status')} | {cell('progress')} | {cell('updated')} | {cell('summary')} |")
        lines.append("")
    (ROOT / "docs/INDEX.md").write_text("\n".join(lines), encoding="utf-8")
    print("wrote docs/INDEX.md")


def list_(status):
    for rel, m in rows():
        if status and m.get("status") != status:
            continue
        print(f"{rel} | {m.get('status')} | {m.get('progress', '')} | {m.get('summary')}")


def set_keys(text, updates):
    meta = FM.match(text)
    if not meta:
        sys.exit("no header; add one first")
    body = meta.group(1).splitlines()
    for k, v in updates.items():
        line = f"{k}: {v}"
        idx = next((i for i, l in enumerate(body) if l.startswith(k + ":")), None)
        if idx is None:
            body.append(line)
        else:
            body[idx] = line
    return "---\n" + "\n".join(body) + "\n---\n" + text[meta.end():]


def dest_for(rel, status):
    if rel.startswith(SPECS_DIR + "/"):
        dst = Path(rel)
    elif rel.startswith(".kiro/specs/"):
        dst = Path(SPECS_DIR) / rel[len(".kiro/specs/"):]
    else:
        dst = Path(ARCHIVE_DIR) / Path(rel).name
    if status == "deprecated" and not dst.stem.endswith("-deprecated"):
        dst = dst.with_name(dst.stem + "-deprecated" + dst.suffix)
    return dst.as_posix()


def archive(paths, reason):
    for p in paths:
        src = Path(p).resolve()
        targets = sorted(src.rglob("*.md")) if src.is_dir() else [src]
        for f in targets:
            rel = f.relative_to(ROOT).as_posix()
            meta = parse(f.read_text(encoding="utf-8"))
            if not meta or meta.get("status") not in ARCHIVED:
                sys.exit(f"{rel}: set status to done or deprecated before archiving")
            f.write_text(set_keys(f.read_text(encoding="utf-8"), {"archived": today(), "reason": f'"{reason}"'}), encoding="utf-8")
            dest = dest_for(rel, meta["status"])
            dst = ROOT / dest
            dst.parent.mkdir(parents=True, exist_ok=True)
            tracked = subprocess.run(["git", "ls-files", "--error-unmatch", rel], cwd=ROOT, capture_output=True).returncode == 0
            subprocess.run(["git", "mv", rel, str(dst)] if tracked else ["mv", str(f), str(dst)], cwd=ROOT, check=True)
            print(f"{rel} -> {dest}")
    print("Now fix links to the moved files (grep for the old path), then run: check && index")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("check"); sub.add_parser("index")
    l = sub.add_parser("list"); l.add_argument("--status")
    a = sub.add_parser("archive"); a.add_argument("paths", nargs="+"); a.add_argument("--reason", required=True)
    args = ap.parse_args()
    if args.cmd == "check": sys.exit(check())
    elif args.cmd == "index": index()
    elif args.cmd == "list": list_(args.status)
    else: archive(args.paths, args.reason)
